### ISSUE TITLE
Line breaks in description

### ISSUE THREAD

**Issue by ringersoll** [Nclose-ZA/elastalert_hive_alerter#5]
Is it possible to add line breaks so the description in Hive can multiple lines like is possible in email alerts?

**Comment by danielbrowne** [comment]
If I include a "\n" newline character in the description field, it does seem to be passed to thehive4py.models.Alert as such. What happens if you for example set "description" in the "hive_alert_config" key of a rule to "test\ntest"?

**Comment by danielbrowne** [comment]
In that case I think this is likely an issue with TheHive4py and should be raised there. 

There is a workaround you could try: make your newline have 2 backslashes, eg. "test\\ntest". This is because TheHive4py makes this data into JSON for use with TheHive API and it is possible that the single backslash simply puts a newline in the JSON, not in the data of the JSON field.

**Comment by MarcusGCY** [comment]
What happen if we use the yaml line break ? Values can span multiple lines using | or > within yaml but not sure how TheHive4py handle it.

**Comment by MarcusGCY** [comment]
> What happen if we use the yaml line break ? Values can span multiple lines using | or > within yaml but not sure how TheHive4py handle it.

So I found out if you do > or | with double enter it will show as newline in hive .

example : 
`
 description: >
      {match[threatInfo][summary]}


      device name: {match[deviceInfo][deviceName]}


      userid: {match[deviceInfo][userID]}`
